name: Check for broken links on site

on:
  workflow_run:
    workflows: [Deploy site]
    types: [completed]

jobs:
  check-links-on-site:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-based-on-the-conclusion-of-another-workflow
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    # available images: https://github.com/actions/runner-images#available-images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Install pixi 🦊
        uses: prefix-dev/setup-pixi@v0.9.3
        with:
          pixi-version: latest
          cache: true
      - name: Update _config.yml ⚙️
        uses: fjogeleit/yaml-update-action@main
        with:
          commitChange: false
          valueFile: "_config.yml"
          changes: |
            {
              "giscus.repo": "${{ github.repository }}",
              "baseurl": ""
            }
      - name: Install dependencies 📦
        run: pixi run install
      - name: Build site 🔧
        run: |
          export JEKYLL_ENV=production
          pixi run build
      - name: Purge unused CSS 🧹
        run: pixi run purgecss
      - name: Link Checker 🔗
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          # only check local links
          args: --offline --remap '_site(/?.*)/assets/(.*) _site/assets/$2' --verbose --no-progress '_site/**/*.html'
