name: Update Starred Repos

on:
  schedule:
    - cron: "0 0 * * 0"   # runs weekly
  workflow_dispatch:       # lets you run manually from Actions tab

jobs:
  update-starred:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Fetch starred repos
        run: |
          curl -s -H "Accept: application/vnd.github+json" \
               https://api.github.com/users/ARC345/starred \
            > _data/starred.json

      - name: Convert JSON to YAML
        run: |
          npm install -g json2yaml
          echo "github_users: []" > _data/repos.yml
          echo "repo_description_lines_max: 3" >> _data/repos.yml
          echo "github_repos:" >> _data/repos.yml
          cat _data/starred.json | jq -r '.[].full_name' | sed 's/^/  - /' >> _data/repos.yml

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add _data/repos.yml
          git commit -m "Update repos with starred repos" || echo "No changes"
          git push
