name: Update Pinned Repos

on:
  schedule:
    - cron: "0 0 * * 0" # every Sunday midnight UTC
  workflow_dispatch:

jobs:
  update-pinned:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq and yq
        run: sudo apt-get update && sudo apt-get install -y jq yq

      - name: Fetch pinned repos
        run: |
          curl -s -H "Authorization: bearer ${{ secrets.GH_TOKEN }}" \
               -H "Content-Type: application/json" \
               -X POST \
               -d '{"query":"{ user(login: \"ARC345\") { pinnedItems(first: 6, types: REPOSITORY) { nodes { ... on Repository { nameWithOwner } } } } }"}' \
               https://api.github.com/graphql \
          | jq -r '.data.user.pinnedItems.nodes[].nameWithOwner' > pinned.txt

      - name: Update github_repos in repositories.yml
        run: |
          echo "github_repos:" > new_repos.yml
          sed 's/^/  - /' pinned.txt >> new_repos.yml
          yq eval-all 'select(fileIndex==0) *+ select(fileIndex==1)' _data/repositories.yml new_repos.yml > tmp.yml
          mv tmp.yml _data/repositories.yml

      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github-actions.github.com"
          git add _data/repositories.yml
          git diff --cached --quiet || git commit -m "Update github_repos with pinned repos"
          git push
